<?php
$library_path="../nesote/library/";
$controller_path="controller/";
$model_path="../model/";
$view_path="view/";
$cache_path="../cache/";
$config_path="../config/";
$restricted_mode="false";
//$salt_password='td}-KkNf!@Oe';
?>
