<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9222830bd963cf55c66cae9e993289f2
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'Ipify\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ipify\\' => 
        array (
            0 => __DIR__ . '/..' . '/benjamin-smith/php-ipify/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'R' => 
        array (
            'Requests' => 
            array (
                0 => __DIR__ . '/..' . '/rmccue/requests/library',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9222830bd963cf55c66cae9e993289f2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9222830bd963cf55c66cae9e993289f2::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit9222830bd963cf55c66cae9e993289f2::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
