<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Ipify\\' => array($vendorDir . '/benjamin-smith/php-ipify/src'),
);
